include ../main.mk

# Paths
RTL_PATH = ../../submodules/MIRISCV/miriscv/rtl
INC_PATH = $(RTL_PATH)/include
TB_PATH = ./tb
OUTPUT_PATH =  build/out/verilator

#  Files
TEST_PROG = program.hex
COMPILE_LOG = compile.log
RUN_LOG = run.log
WAVEFORM = run_waves.vcd
SV_TOP = miriscv_tb_top
